name: MeetupsApi CI/CD prod

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  actions: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Install Serverless
        run: npm install -g serverless
      - name: serverless deploy production
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          SERVERLESS_ORG: ${{ secrets.SERVERLESS_ORG }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          # deploy to prod
          npm run deploy:prod
          # invoke specific function to load production data
          npm run invoke:prod-data